/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.io.*;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ashra
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reserve = new javax.swing.JDialog();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb = new javax.swing.JTable();
        day = new javax.swing.JComboBox<>();
        month = new javax.swing.JComboBox<>();
        year = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        spindur = new javax.swing.JSpinner();
        spincap = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        activitycbox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        disp = new javax.swing.JButton();
        srcbtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        roomtype = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();
        abt = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        payment = new javax.swing.JDialog();
        payment_status = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        reservebtn = new javax.swing.JButton();
        faciliiesbtn = new javax.swing.JButton();
        abtbtn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        reserve.setMinimumSize(new java.awt.Dimension(1920, 1080));
        reserve.setResizable(false);
        reserve.getContentPane().setLayout(null);

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("BlackChancery", 0, 36)); // NOI18N
        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        reserve.getContentPane().add(jButton4);
        jButton4.setBounds(1559, 955, 270, 70);

        tb.setFont(new java.awt.Font("BlackChancery", 0, 24)); // NOI18N
        tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ROOMID", "CAPACITY", "STATUS", "COST", "AC"
            }
        ));
        tb.setToolTipText("");
        jScrollPane1.setViewportView(tb);

        reserve.getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(70, 210, 910, 600);

        day.setFont(new java.awt.Font("BlackChancery", 0, 24)); // NOI18N
        day.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        reserve.getContentPane().add(day);
        day.setBounds(1530, 140, 80, 40);

        month.setFont(new java.awt.Font("BlackChancery", 0, 24)); // NOI18N
        month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        reserve.getContentPane().add(month);
        month.setBounds(1630, 140, 80, 40);

        year.setFont(new java.awt.Font("BlackChancery", 0, 24)); // NOI18N
        year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2018", "2019", "2020" }));
        year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearActionPerformed(evt);
            }
        });
        reserve.getContentPane().add(year);
        year.setBounds(1730, 140, 80, 40);

        jLabel3.setFont(new java.awt.Font("BlackChancery", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Check In Date");
        reserve.getContentPane().add(jLabel3);
        jLabel3.setBounds(1320, 140, 190, 40);

        jLabel5.setFont(new java.awt.Font("BlackChancery", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Duration");
        reserve.getContentPane().add(jLabel5);
        jLabel5.setBounds(1320, 200, 180, 50);

        spindur.setFont(new java.awt.Font("BlackChancery", 0, 24)); // NOI18N
        spindur.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
        reserve.getContentPane().add(spindur);
        spindur.setBounds(1530, 210, 100, 30);

        spincap.setFont(new java.awt.Font("BlackChancery", 0, 24)); // NOI18N
        spincap.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        reserve.getContentPane().add(spincap);
        spincap.setBounds(1530, 270, 100, 30);

        jLabel6.setFont(new java.awt.Font("BlackChancery", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Activity Package");
        reserve.getContentPane().add(jLabel6);
        jLabel6.setBounds(1300, 390, 170, 40);

        activitycbox.setFont(new java.awt.Font("BlackChancery", 0, 24)); // NOI18N
        activitycbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Minimal", "Standard", "Deluxe", "Supreme", "Complete", " " }));
        reserve.getContentPane().add(activitycbox);
        activitycbox.setBounds(1530, 390, 320, 40);

        jLabel7.setFont(new java.awt.Font("BlackChancery", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("No. of Guests");
        reserve.getContentPane().add(jLabel7);
        jLabel7.setBounds(1330, 270, 150, 40);

        disp.setBackground(new java.awt.Color(255, 255, 255));
        disp.setFont(new java.awt.Font("BlackChancery", 0, 36)); // NOI18N
        disp.setText("Display Rooms");
        disp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dispActionPerformed(evt);
            }
        });
        reserve.getContentPane().add(disp);
        disp.setBounds(1120, 500, 270, 60);

        srcbtn.setFont(new java.awt.Font("BlackChancery", 0, 36)); // NOI18N
        srcbtn.setText("Search");
        srcbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srcbtnActionPerformed(evt);
            }
        });
        reserve.getContentPane().add(srcbtn);
        srcbtn.setBounds(1470, 500, 280, 60);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("BlackChancery", 0, 36)); // NOI18N
        jButton2.setText("Proceed to Payment");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        reserve.getContentPane().add(jButton2);
        jButton2.setBounds(1240, 610, 360, 70);

        roomtype.setFont(new java.awt.Font("BlackChancery", 0, 24)); // NOI18N
        roomtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Standard", "Deluxe", "Superior", "Executive" }));
        reserve.getContentPane().add(roomtype);
        roomtype.setBounds(1530, 330, 320, 40);

        jLabel10.setFont(new java.awt.Font("BlackChancery", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Type");
        reserve.getContentPane().add(jLabel10);
        jLabel10.setBounds(1300, 330, 170, 40);

        bg.setFont(new java.awt.Font("BlackChancery", 0, 24)); // NOI18N
        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/Payment.png"))); // NOI18N
        bg.setText("jLabel4");
        reserve.getContentPane().add(bg);
        bg.setBounds(0, 0, 1920, 1080);

        abt.setMinimumSize(new java.awt.Dimension(1920, 1080));
        abt.getContentPane().setLayout(null);

        jLabel8.setFont(new java.awt.Font("BlackChancery", 0, 72)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("About");
        abt.getContentPane().add(jLabel8);
        jLabel8.setBounds(810, 40, 210, 70);

        jLabel9.setFont(new java.awt.Font("BlackChancery", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("<html><p>Established in 2007, exotica has been one of the best service providers when it comes to holidaying. Being situated in Arambol,North Goa has never failed to attract customers across the state. With lots of fun packages that people can avail, its been the best prioritized resort amongst alll the ones located in and around the same city</p></html>");
        abt.getContentPane().add(jLabel9);
        jLabel9.setBounds(130, 180, 690, 370);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("BlackChancery", 0, 48)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        abt.getContentPane().add(jButton1);
        jButton1.setBounds(720, 650, 280, 80);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/about.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        abt.getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 1920, 1080);

        payment.setMinimumSize(new java.awt.Dimension(1920, 1080));
        payment.setPreferredSize(new java.awt.Dimension(1920, 1080));
        payment.getContentPane().setLayout(null);

        payment_status.setText("LABEL FOR DISPLAYING STATUS");
        payment.getContentPane().add(payment_status);
        payment_status.setBounds(120, 460, 240, 520);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/reserve.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        payment.getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 1920, 1080);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Magician's Daughter", 0, 72)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("WELCOME TO EXOTICA");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(500, 30, 1030, 140);

        reservebtn.setBackground(new java.awt.Color(0, 0, 0));
        reservebtn.setFont(new java.awt.Font("BlackChancery", 0, 36)); // NOI18N
        reservebtn.setForeground(new java.awt.Color(255, 255, 255));
        reservebtn.setText("Reserve a Room");
        reservebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservebtnActionPerformed(evt);
            }
        });
        getContentPane().add(reservebtn);
        reservebtn.setBounds(1450, 230, 370, 60);

        faciliiesbtn.setBackground(new java.awt.Color(0, 0, 0));
        faciliiesbtn.setFont(new java.awt.Font("BlackChancery", 0, 36)); // NOI18N
        faciliiesbtn.setForeground(new java.awt.Color(255, 255, 255));
        faciliiesbtn.setText("View Facilities");
        getContentPane().add(faciliiesbtn);
        faciliiesbtn.setBounds(1450, 330, 370, 60);

        abtbtn.setBackground(new java.awt.Color(0, 0, 0));
        abtbtn.setFont(new java.awt.Font("BlackChancery", 0, 36)); // NOI18N
        abtbtn.setForeground(new java.awt.Color(255, 255, 255));
        abtbtn.setText("About");
        abtbtn.setToolTipText("");
        abtbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abtbtnActionPerformed(evt);
            }
        });
        getContentPane().add(abtbtn);
        abtbtn.setBounds(1450, 440, 370, 60);

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("BlackChancery", 0, 36)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("View Reservation Status");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(80, 220, 410, 60);

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setFont(new java.awt.Font("BlackChancery", 0, 36)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Check Out");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(80, 310, 410, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/main.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1920, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents
static final String DB_URL="jdbc:mysql://localhost:3306/resort?autoReconnect=true&useSSL=false";
static final String USER="root";
static final String PASS="ashray123";
Connection con;
ResultSet rs;
Statement stmt;
    private void reservebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservebtnActionPerformed
try{
    cust_id = new String(Files.readAllBytes(Paths.get("C:\\Users\\ashra\\OneDrive\\Documents\\NetBeansProjects\\SylvanGladeResort\\src\\Main\\filename.txt")));
    Class.forName("java.sql.Driver");
    con=DriverManager.getConnection(DB_URL,USER,PASS);
    stmt=con.createStatement();
    String check = "SELECT RESERVATIONID FROM RESERVATION WHERE CUSTOMERID='"+cust_id+"';";
    rs=stmt.executeQuery(check);
    if(rs.first()==false){
         reserve.setVisible(true);
         this.setVisible(false);
    }
    else{
        JOptionPane.showMessageDialog(this,"YOU HAVE ALREADY RESERVED A ROOM");
        reservebtn.disable();
    }
}

catch(Exception e){
    e.printStackTrace();
}


// TODO add your handling code here:
    }//GEN-LAST:event_reservebtnActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
  reserve.setVisible(false);
        this.setVisible(true);

// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearActionPerformed

    private void dispActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dispActionPerformed

DefaultTableModel model = (DefaultTableModel) tb.getModel();                            //SETS MODEL TO CURRENT TABLE
try{   
    //TO DISPLAY ALL AVAILABLE ROOMS
    model.setRowCount(0);
    Class.forName("java.sql.Driver");
    con=DriverManager.getConnection(DB_URL, USER, PASS);
    stmt=con.createStatement();
    String query="SELECT ROOMID,CAPACITY,STATUS,COST,TYPE FROM ROOMS WHERE STATUS='A'";                     //QUERY TO GET ALL ROOMS WHICH ARE AVAILABLE
    rs=stmt.executeQuery(query);
    while(rs.next()){
        model.addRow(new Object[]{rs.getString(1),rs.getInt(2),rs.getString(3),rs.getInt(4),rs.getString(5)});
    }
   
}
catch(Exception e){
    e.printStackTrace();
}




// TODO add your handling code here:
    }//GEN-LAST:event_dispActionPerformed

    private void abtbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abtbtnActionPerformed
this.setVisible(false);
abt.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_abtbtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
this.setVisible(true);
abt.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void srcbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srcbtnActionPerformed

int capacity=(int) spincap.getValue();
String ac = new String();
String type=(String) roomtype.getSelectedItem();

DefaultTableModel model = (DefaultTableModel) tb.getModel();
model.setRowCount(0);
try{
      Class.forName("java.sql.Driver");
    con=DriverManager.getConnection(DB_URL, USER, PASS);
    stmt=con.createStatement();
    String query = "SELECT ROOMID,CAPACITY,STATUS,COST,TYPE FROM ROOMS WHERE CAPACITY="+capacity+" AND TYPE='"+type+"';";
    rs=stmt.executeQuery(query);
    while(rs.next()){
        String roomid = rs.getString(1);
        int cap = rs.getInt(2);
        String stat = rs.getString(3);
        int cst=rs.getInt(4);
        String a_c=rs.getString(5);
        model.addRow(new Object[]{roomid,cap,stat,cst,a_c});
    }
         if(model.getRowCount()==0){
            JOptionPane.showMessageDialog(this,"No rooms available");
        }


}
catch(Exception e){
    JOptionPane.showMessageDialog(this,"Invalid Entry");
    model.setRowCount(0);
}






// TODO add your handling code here:
    }//GEN-LAST:event_srcbtnActionPerformed
public String incpay(String a){
    int res=0;
    String cut=a.substring(1);
    res=Integer.parseInt(cut);
    res+=1;
    String initial="P";
    String initial_append=Integer.toString(res);
    String result=initial+initial_append;
    return result;
}
public String selectactivity(int activityindex){
  String activity="";
    switch(activityindex){
       case 0: activity="A001";
               break;
       case 1: activity="A002";
               break;
       case 2: activity="A003";
               break;
       case 3: activity="A004";
               break;
       case 4: activity="A005";
               break;
       case 5: activity="A006";
               break;       
       default: activity="A001";
               break;              
   } 
return activity;
}

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
try {
 cust_id = new String(Files.readAllBytes(Paths.get("C:\\Users\\ashra\\OneDrive\\Documents\\NetBeansProjects\\SylvanGladeResort\\src\\Main\\filename.txt")));
} catch (IOException ex) {
 ex.printStackTrace();
 }
int d = Integer.parseInt((String) day.getSelectedItem());
int m =  Integer.parseInt((String)month.getSelectedItem());
int y = Integer.parseInt((String) year.getSelectedItem());
int pkgindex=activitycbox.getSelectedIndex();
String activity=selectactivity(pkgindex);
String cdate = ""+y+"/"+m+"/"+""+d;
duration=(int)spindur.getValue();
int coutday=d+duration;
String cout=""+y+"/"+m+"/"+""+coutday;
DefaultTableModel bookmodel = (DefaultTableModel) tb.getModel();
int selectedRowIndex = tb.getSelectedRow();
int selectedColIndex=tb.getSelectedRow();
String roomid = (String) tb.getModel().getValueAt(selectedRowIndex,selectedColIndex);

int reserveid=0,resid=0;
try{
    Class.forName("java.sql.Driver");
    con=DriverManager.getConnection(DB_URL, USER, PASS);
    stmt=con.createStatement();
    String query="SELECT * FROM RESERVATION";
    rs=stmt.executeQuery(query);
    rs.last();
    resid=rs.getInt(1);
    reserveid=resid+1;
        String update_room="UPDATE ROOMS SET STATUS ='R' WHERE ROOMID='"+roomid+"';";
    stmt.executeUpdate(update_room);
    String insert="INSERT INTO RESERVATION VALUES("+reserveid+",'"+cdate+"','"+cout+"','"+roomid+"','"+activity+"','"+cust_id+"')";
    stmt.executeUpdate(insert);
    String pay="SELECT PAYMENTID FROM PAYMENT";
    ResultSet rs2=stmt.executeQuery(pay);
    rs2.last();
    String lastpid=rs2.getString(1);
    String nextpid=incpay(lastpid);
    String generate_new_payment="INSERT INTO PAYMENT(PAYMENTID,CUSTOMERID,RESERVATIONID) VALUES('"+nextpid+"','"+cust_id+"',"+reserveid+");";
    stmt.executeUpdate(generate_new_payment);
    JOptionPane.showMessageDialog(this,"Booking was Successful");
    reserve.setVisible(false);
    payment.setVisible(true);
    String calculate_amt="CALL CalculateFinalAmount('"+cust_id+"');";
    stmt.executeQuery(calculate_amt);
    String display_payment_status="SELECT C.FNAME,C.LNAME,C.EMAIL,R.ROOMID,P.AMOUNT,RS.CHECKIN,RS.CHECKOUT "
            + "FROM CUSTOMER C,ROOMS R,RESERVATION RS "
            + "WHERE C.CUSTOMERID=P.CUSTOMERID "
            + "AND C.CUSTOMERID=RS.CUSTOMERID "
            + "AND RS.ROOMID=R.ROOMID "
            + "AND P.RESERVATIONID=RS.RESERVATIONID "
            + "AND C.CUSTOMERID='"+cust_id+"';";
    rs=stmt.executeQuery(display_payment_status);
    rs.first();
    String fname,lname,email,rmid,checkin,checkout;
    fname=rs.getString(1);
    lname=rs.getString(2);
    email=rs.getString(3);
    rmid=rs.getString(4);
    int amount=rs.getInt(5);
    checkin=rs.getString(6);
    checkout=rs.getString(7);   
    String disp_status="";
    payment_status.setText(disp_status);
}
catch(Exception e){
    e.printStackTrace();
     JOptionPane.showMessageDialog(this,"Unsuccessful Booking please try again");
}



// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
try{
    cust_id = new String(Files.readAllBytes(Paths.get("C:\\Users\\ashra\\OneDrive\\Documents\\NetBeansProjects\\SylvanGladeResort\\src\\Main\\filename.txt")));
    Class.forName("java.sql.Driver");
    con=DriverManager.getConnection(DB_URL, USER, PASS);
    stmt=con.createStatement();
    String reservationstatus="select c.customerid,c.fname,c.lname,r.reservationid,r.checkin,r.checkout,rm.roomid,rm.type,rm.capacity from customer c,reservation r, rooms rm where c.customerid=r.customerid and r.roomid=rm.roomid and c.customerid='"+cust_id+"';";
    rs=stmt.executeQuery(reservationstatus);
    rs.first();
    String customerid=rs.getString(1);
    String fname=rs.getString(2);
    String lname=rs.getString(3);
    int reservationid=rs.getInt(4);
    String checkin=rs.getString(5);
    String checkout=rs.getString(6);
    String roomid=rs.getString(7);
    String type=rs.getString(8);
    int capacity=rs.getInt(9);
    String printstatus="CustomerID:"+customerid+"\nName:"+fname+" "+lname+"\nReservationID:"+reservationid+"\nCheck In Date:"+checkin+"\nCheck Out Date:"+checkout+"\nRoomID:"+roomid+"\nType:"+type+"\nCapacity:"+capacity+"\n";
    JOptionPane.showMessageDialog(this,printstatus);
}
catch(Exception e){
    e.printStackTrace();
}
// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    String cust_id;
    int duration;

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog abt;
    private javax.swing.JButton abtbtn;
    private javax.swing.JComboBox<String> activitycbox;
    private javax.swing.JLabel bg;
    private javax.swing.JComboBox<String> day;
    private javax.swing.JButton disp;
    private javax.swing.JButton faciliiesbtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> month;
    private javax.swing.JDialog payment;
    private javax.swing.JLabel payment_status;
    private javax.swing.JDialog reserve;
    private javax.swing.JButton reservebtn;
    private javax.swing.JComboBox<String> roomtype;
    private javax.swing.JSpinner spincap;
    private javax.swing.JSpinner spindur;
    private javax.swing.JButton srcbtn;
    private javax.swing.JTable tb;
    private javax.swing.JComboBox<String> year;
    // End of variables declaration//GEN-END:variables
}
