/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.awt.Color;
import javax.swing.JOptionPane;
import java.sql.*;
/**
 *
 * @author ashra
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        p = new javax.swing.JLabel();
        cp = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        fname = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        custid = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        confirmpwd = new javax.swing.JPasswordField();
        pwd = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(null);

        jPanel1.setMinimumSize(new java.awt.Dimension(1920, 1080));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1920, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(1974, 0, 1920, 0);

        jLabel2.setFont(new java.awt.Font("BlackChancery", 0, 126)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Register");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(800, 50, 440, 160);

        jLabel3.setFont(new java.awt.Font("BlackChancery", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CustomerID");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 240, 220, 70);

        jLabel4.setFont(new java.awt.Font("BlackChancery", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Address");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(1020, 350, 220, 70);

        p.setFont(new java.awt.Font("BlackChancery", 0, 36)); // NOI18N
        p.setForeground(new java.awt.Color(255, 255, 255));
        p.setText("Password");
        p.setToolTipText("");
        getContentPane().add(p);
        p.setBounds(80, 340, 220, 70);

        cp.setFont(new java.awt.Font("BlackChancery", 0, 28)); // NOI18N
        cp.setForeground(new java.awt.Color(255, 255, 255));
        cp.setText("Confirm Password");
        getContentPane().add(cp);
        cp.setBounds(80, 440, 220, 70);

        jLabel7.setFont(new java.awt.Font("BlackChancery", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("First Name");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(80, 550, 220, 70);

        jLabel8.setFont(new java.awt.Font("BlackChancery", 0, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("LastName");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(80, 660, 220, 70);

        jLabel9.setFont(new java.awt.Font("BlackChancery", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Email");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(80, 770, 220, 70);

        jLabel10.setFont(new java.awt.Font("BlackChancery", 0, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Phone");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(1030, 240, 220, 70);

        phone.setFont(new java.awt.Font("BlackChancery", 0, 30)); // NOI18N
        getContentPane().add(phone);
        phone.setBounds(1300, 250, 420, 50);

        email.setFont(new java.awt.Font("BlackChancery", 0, 30)); // NOI18N
        getContentPane().add(email);
        email.setBounds(310, 780, 420, 50);

        fname.setFont(new java.awt.Font("BlackChancery", 0, 30)); // NOI18N
        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });
        getContentPane().add(fname);
        fname.setBounds(310, 560, 420, 50);

        lname.setFont(new java.awt.Font("BlackChancery", 0, 30)); // NOI18N
        getContentPane().add(lname);
        lname.setBounds(310, 670, 420, 50);

        custid.setFont(new java.awt.Font("BlackChancery", 0, 30)); // NOI18N
        getContentPane().add(custid);
        custid.setBounds(310, 250, 420, 50);

        address.setColumns(20);
        address.setFont(new java.awt.Font("BlackChancery", 0, 30)); // NOI18N
        address.setRows(5);
        jScrollPane1.setViewportView(address);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(1300, 360, 420, 250);

        jButton1.setBackground(new java.awt.Color(255, 204, 255));
        jButton1.setFont(new java.awt.Font("BlackChancery", 0, 48)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1250, 830, 510, 60);

        confirmpwd.setFont(new java.awt.Font("BlackChancery", 0, 28)); // NOI18N
        confirmpwd.setEchoChar('*');
        getContentPane().add(confirmpwd);
        confirmpwd.setBounds(310, 440, 420, 60);

        pwd.setFont(new java.awt.Font("BlackChancery", 0, 28)); // NOI18N
        pwd.setEchoChar('*');
        getContentPane().add(pwd);
        pwd.setBounds(310, 350, 420, 60);

        jButton2.setFont(new java.awt.Font("BlackChancery", 0, 48)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(1260, 930, 500, 60);

        bg.setFont(new java.awt.Font("BlackChancery", 0, 30)); // NOI18N
        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/registerbg.jpg"))); // NOI18N
        getContentPane().add(bg);
        bg.setBounds(0, 0, 1921, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents
static final String DB_URL="jdbc:mysql://localhost/resort";
static final String USER="root";
static final String PASS="ashray123";
Connection con;
ResultSet rs;
Statement stmt;
    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String cid=custid.getText();
String password=pwd.getText(); 
String confpassword=confirmpwd.getText();
String f_name=fname.getText();
String l_name=lname.getText();
String em=email.getText();
String add=address.getText();
int ph = Integer.parseInt(phone.getText());
if(password.equals(confpassword)){
    try{
        Class.forName("java.sql.Driver");
            con=DriverManager.getConnection(DB_URL,USER,PASS);
            String sql;
            sql="INSERT INTO CUSTOMER VALUES('"+cid+"','"+password+"','"+f_name+"','"+l_name+"','"+em+"','"+add+"',"+ph+");";
            stmt=con.createStatement();
            stmt.executeUpdate(sql);
            JOptionPane.showMessageDialog(this,"Registration Successful");
            this.setVisible(false);
            LoginPage l = new LoginPage();
            l.setVisible(true);
    }
    catch(Exception e){
        e.printStackTrace();
    }
}
else{
    JOptionPane.showMessageDialog(this,"Password does not match");
    cp.setForeground(Color.red);
    p.setForeground(Color.red);
}




// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
LoginPage l =  new LoginPage();
l.setVisible(true);
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea address;
    private javax.swing.JLabel bg;
    private javax.swing.JPasswordField confirmpwd;
    private javax.swing.JLabel cp;
    private javax.swing.JTextField custid;
    private javax.swing.JTextField email;
    private javax.swing.JTextField fname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lname;
    private javax.swing.JLabel p;
    private javax.swing.JTextField phone;
    private javax.swing.JPasswordField pwd;
    // End of variables declaration//GEN-END:variables
}
